# Generated by Django 4.1.4 on 2023-01-04 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0002_alter_trainings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrolls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enroll_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
