# Generated by Django 4.1.4 on 2023-01-04 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0002_alter_sections_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_sections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('order_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('files', models.FileField(upload_to='uploads/')),
                ('urls', models.URLField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.sections')),
            ],
        ),
    ]
