# Generated by Django 4.1.4 on 2023-01-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
